### ISSUE TITLE
Documentation incorrect?

### ISSUE THREAD

**Issue by ForsakenHarmony** [GGAlanSmithee/Entities#59]
you can't use 
```
const sys = entityManager.registerLogicSystem('system', [ comp1, comp2 ], system)
```
at least the name part

**Comment by GGAlanSmithee** [comment]
Hey @ForsakenHarmony, thanks for raising this issue.

You are right, as it stands the documentation is wrong. `EntityManager.register*System` does not take a `name` parameter, and I will update the docs to reflect this. There were quite a lot of API changes before v2, so I'll blame that :D.

BTW, do you need to be able to have a deterministic name as a system key?

**Comment by ForsakenHarmony** [comment]
uhh no, I don't think I need it

btw, I created typings for this project, not sure if they are 100% accurate tho: [gist](https://gist.github.com/ForsakenHarmony/33ef7c4d7cba7a08d5fa2667b5b1b31e)

**Comment by GGAlanSmithee** [comment]
@ForsakenHarmony the docs have been updated.

> btw, I created typings for this project, not sure if they are 100% accurate tho: gist

Wow! That is great. From looking at it briefly it seems correct to mee. I was previously using `flow` but abandoned it due to some immaturity at the time. I will consider adding typescript at a later release.

**Comment by GGAlanSmithee** [comment]
@ForsakenHarmony I will close this issue as it is fixed. I took the liberty to [link to your gist](http://ggalansmithee.github.io/Entities/#/?id=typings) from the docs. Hope you don't mind.

**Comment by ForsakenHarmony** [comment]
yea, I don't mind
