### ISSUE TITLE
Add a d.ts file for TypeScript users

### ISSUE THREAD

**Issue by GGAlanSmithee** [GGAlanSmithee/Entities#83]
1. Can probably be based on the awesome [gist](https://gist.github.com/ForsakenHarmony/33ef7c4d7cba7a08d5fa2667b5b1b31e) by @ForsakenHarmony and updated to version 3
2. Add to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/), see [this](http://blog.wolksoftware.com/contributing-to-definitelytyped)

**Comment by ForsakenHarmony** [comment]
you don't necessarily have to add it to definitely typed, you can also just use the `typings` key in `package.json`

**Comment by GGAlanSmithee** [comment]
@ForsakenHarmony Thanks for the info, will probably do this 👍

**Comment by GGAlanSmithee** [comment]
This is now implemented:

1. See [src/index.d.ts](https://github.com/GGAlanSmithee/Entities/blob/types/src/index.d.ts)
2. Added [typescript "tests" to varify typings](https://github.com/GGAlanSmithee/Entities/blob/types/test/typescript/index.ts)
3. Added to `types` in [`package.json`](https://github.com/GGAlanSmithee/Entities/blob/types/package.json#L8)

This will momentarily be merged to dev and released to npm under a beta tag. 

As a side note, this work has led to some significant API simplifications/improvements, bug fixes and refactorization, which is great! Also, I removed everything but `EntityManager` and `SystemType` from the public module export. All other classes are now to be considered a private implementation detail, which gives us more room for changing it in the future. (starting from v.3)

**Comment by GGAlanSmithee** [comment]
#94 now merged in dev and released to npm as version 3.0.0-beta.1 under the beta tag.
